version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: project-3-ecr-repo
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:235816292640:secret:codebuild-docker-accesstoken-znhMBo --query 'SecretString' --output text | jq -r '.DOCKER_USERNAME')
      - DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:235816292640:secret:codebuild-docker-accesstoken-znhMBo --query 'SecretString' --output text | jq -r '.DOCKER_PASSWORD')
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG ./analytics/.
      - echo docker images
      - docker images
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG